export const knownStructureRegistry = Object.freeze([
  {
    id: 'proxy-calls',
    title: 'Proxy Calls',
    categoryGroup: 'obfuscation',
    category: 'calls',
    description: 'Matches wrapper functions that only forward arguments into another call.',
    codeExample: [
      'function proxyCall(handler, a, b) {',
      '  return handler(a, b);',
      '}',
      '',
      'const sum = (left, right) => left + right;',
      'const total = proxyCall(sum, 2, 3);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveProxyCallsMatch',
    transformName: 'resolveProxyCallsTransform',
    transformEnabled: true,
    moduleName: 'resolveProxyCalls',
  },
  {
    id: 'proxy-variables',
    title: 'Proxy Variables',
    categoryGroup: 'obfuscation',
    category: 'variables',
    description: 'Matches identifier aliases that point directly at another identifier.',
    codeExample: [
      'const originalValue = computeScore(input);',
      'const aliasedValue = originalValue;',
      '',
      'console.log(aliasedValue);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveProxyVariablesMatch',
    transformName: 'resolveProxyVariablesTransform',
    transformEnabled: true,
    moduleName: 'resolveProxyVariables',
  },
  {
    id: 'proxy-references',
    title: 'Proxy References',
    categoryGroup: 'obfuscation',
    category: 'variables',
    description: 'Matches proxy declarations that redirect reads to another identifier or member expression.',
    codeExample: [
      'const state = {',
      "  token: 'abc123',",
      '};',
      '',
      'const tokenRef = state.token;',
      'useToken(tokenRef);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveProxyReferencesMatch',
    transformName: 'resolveProxyReferencesTransform',
    transformEnabled: true,
    moduleName: 'resolveProxyReferences',
  },
  {
    id: 'wrapped-value-shells',
    title: 'Wrapped Value Shells',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches function shells whose only job is to return a wrapped value.',
    codeExample: [
      'function revealValue() {',
      "  return 'decoded';",
      '}',
      '',
      'const message = revealValue();',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceFunctionShellsWithWrappedValueMatch',
    transformName: 'replaceFunctionShellsWithWrappedValueTransform',
    transformEnabled: true,
    moduleName: 'replaceFunctionShellsWithWrappedValue',
  },
  {
    id: 'iife-wrappers',
    title: 'IIFE Wrappers',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches immediately invoked wrapper functions that can be unwrapped structurally.',
    codeExample: [
      'const config = (function () {',
      '  const retries = 3;',
      '  return {retries};',
      '}());',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'unwrapIIFEsMatch',
    transformName: 'unwrapIIFEsTransform',
    transformEnabled: true,
    moduleName: 'unwrapIIFEs',
  },
  {
    id: 'template-literal-strings',
    title: 'Template Literal Strings',
    categoryGroup: 'obfuscation',
    category: 'literals',
    description: 'Matches template literals made entirely from static literal content.',
    codeExample: [
      'const label = `debug mode enabled`;',
      'console.log(label);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'parseTemplateLiteralsIntoStringLiteralsMatch',
    transformName: 'parseTemplateLiteralsIntoStringLiteralsTransform',
    transformEnabled: true,
    moduleName: 'parseTemplateLiteralsIntoStringLiterals',
  },
  {
    id: 'fixed-assigned-values',
    title: 'Fixed Assigned Values',
    categoryGroup: 'obfuscation',
    category: 'variables',
    description: 'Matches identifiers assigned a fixed value that can be propagated safely.',
    codeExample: [
      'const statusCode = 200;',
      'const responseCode = statusCode;',
      '',
      'if (responseCode === 200) {',
      "  console.log('ok');",
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceIdentifierWithFixedAssignedValueMatch',
    transformName: 'replaceIdentifierWithFixedAssignedValueTransform',
    transformEnabled: true,
    moduleName: 'replaceIdentifierWithFixedAssignedValue',
  },
  {
    id: 'deterministic-if-statements',
    title: 'Deterministic If Statements',
    categoryGroup: 'obfuscation',
    category: 'conditionals',
    description: 'Matches `if` statements whose branch outcome is statically determined.',
    codeExample: [
      'if (true) {',
      '  runVisibleBranch();',
      '} else {',
      '  runDeadBranch();',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveDeterministicIfStatementsMatch',
    transformName: 'resolveDeterministicIfStatementsTransform',
    transformEnabled: true,
    moduleName: 'resolveDeterministicIfStatements',
  },
  {
    id: 'sequence-rearrangement',
    title: 'Comma Sequences in Returns and If Tests',
    categoryGroup: 'obfuscation',
    category: 'sequences',
    description: 'Matches return statements and `if` tests whose expression is a comma (sequence) expression.',
    codeExample: [
      'const result = (',
      "  logStep('first'),",
      "  logStep('second'),",
      '  finalizeStep()',
      ');',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'rearrangeSequencesMatch',
    transformName: 'rearrangeSequencesTransform',
    transformEnabled: true,
    moduleName: 'rearrangeSequences',
  },
  {
    id: 'switch-rearrangement',
    title: 'Switch Statements With Literal Discriminants',
    categoryGroup: 'obfuscation',
    category: 'control-flow',
    description: 'Matches `switch` statements on an identifier initialized to a literal, with deterministic case-to-case flow.',
    codeExample: [
      'switch (state) {',
      "  case 'init':",
      "    state = 'ready';",
      '    break;',
      "  case 'ready':",
      '    render();',
      '    break;',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'rearrangeSwitchesMatch',
    transformName: 'rearrangeSwitchesTransform',
    transformEnabled: false,
    moduleName: 'rearrangeSwitches',
  },
  {
    id: 'computed-members',
    title: 'Computed Members',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches computed member access and property keys that can be normalized to identifier syntax.',
    codeExample: [
      'const user = {name: "Ada"};',
      "const propertyName = 'name';",
      '',
      'console.log(user[propertyName]);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'normalizeComputedMatch',
    transformName: 'normalizeComputedTransform',
    transformEnabled: true,
    moduleName: 'normalizeComputed',
  },
  {
    id: 'simplify-calls',
    title: 'Call and Apply With This Receiver',
    categoryGroup: 'obfuscation',
    category: 'calls',
    description: 'Matches `.call(this, …)` or `.apply(this, …)` where the first argument is `this` (or an allowed literal), eligible to fold into a direct call.',
    codeExample: [
      'function f() {}',
      '',
      'f.call(this, 1);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'simplifyCallsMatch',
    transformName: 'simplifyCallsTransform',
    transformEnabled: true,
    moduleName: 'simplifyCalls',
  },
  {
    id: 'empty-statements',
    title: 'Empty Statements',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches stray empty statements (`;`) that are not required for control-flow syntax.',
    codeExample: [
      'function example() {',
      '  ;',
      '  return 1;',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'normalizeEmptyStatementsMatch',
    transformName: 'normalizeEmptyStatementsTransform',
    transformEnabled: true,
    moduleName: 'normalizeEmptyStatements',
  },
  {
    id: 'dead-node-declarations',
    title: 'Dead Declarations',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches declarations that appear unused in the AST (may miss external definitions or dynamic reads such as eval or bracket access).',
    codeExample: [
      'function outer() {',
      '  const neverRead = 1;',
      '  return 2;',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'removeDeadNodesMatch',
    transformName: 'removeDeadNodesTransform',
    transformEnabled: true,
    moduleName: 'removeDeadNodes',
  },
  {
    id: 'redundant-block-statements',
    title: 'Redundant Block Statements',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches block statements nested directly inside another block or the program body where flattening is possible.',
    codeExample: [
      '(function () {',
      '  {',
      '    {',
      '      console.log(1);',
      '    }',
      '  }',
      '}());',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'removeRedundantBlockStatementsMatch',
    transformName: 'removeRedundantBlockStatementsTransform',
    transformEnabled: true,
    moduleName: 'removeRedundantBlockStatements',
  },
  {
    id: 'logical-expressions-as-if',
    title: 'Short-Circuit Logical Expression Statements',
    categoryGroup: 'obfuscation',
    category: 'conditionals',
    description: 'Matches expression statements whose top-level expression is `&&` or `||`.',
    codeExample: [
      'const ready = true;',
      'ready && launch();',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceBooleanExpressionsWithIfMatch',
    transformName: 'replaceBooleanExpressionsWithIfTransform',
    transformEnabled: true,
    moduleName: 'replaceBooleanExpressionsWithIf',
  },
  {
    id: 'call-unwrapped-identifier',
    title: 'Identifier-Only Return Wrapper Calls',
    categoryGroup: 'obfuscation',
    category: 'calls',
    description: 'Matches calls to small functions that only return another identifier or trivial expression, eligible for inlining.',
    codeExample: [
      'const value = 1;',
      'function id() {',
      '  return value;',
      '}',
      'id();',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceCallExpressionsWithUnwrappedIdentifierMatch',
    transformName: 'replaceCallExpressionsWithUnwrappedIdentifierTransform',
    transformEnabled: true,
    moduleName: 'replaceCallExpressionsWithUnwrappedIdentifier',
  },
  {
    id: 'eval-string-literals',
    title: 'Eval String Literals',
    categoryGroup: 'obfuscation',
    category: 'literals',
    description: 'Matches `eval` calls whose argument is a string literal; replaces them with parsed AST (no execution of eval).',
    codeExample: [
      "const n = eval('40 + 2');",
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceEvalCallsWithLiteralContentMatch',
    transformName: 'replaceEvalCallsWithLiteralContentTransform',
    transformEnabled: true,
    moduleName: 'replaceEvalCallsWithLiteralContent',
  },
  {
    id: 'iife-literal-shells',
    title: 'IIFE Literal Shells',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches zero-argument IIFEs that only return a literal or identifier, replaceable with that value.',
    codeExample: [
      'const boxed = (function () {',
      '  return 7;',
      '}());',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceFunctionShellsWithWrappedValueIIFEMatch',
    transformName: 'replaceFunctionShellsWithWrappedValueIIFETransform',
    transformEnabled: true,
    moduleName: 'replaceFunctionShellsWithWrappedValueIIFE',
  },
  {
    id: 'fixed-value-after-declaration',
    title: 'Declarations With Later Literal Assignment',
    categoryGroup: 'obfuscation',
    category: 'variables',
    description: 'Matches identifiers declared without an initializer and later assigned exactly one literal value.',
    codeExample: [
      'function f() {',
      '  let v;',
      '  v = 3;',
      '  return v;',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceIdentifierWithFixedValueNotAssignedAtDeclarationMatch',
    transformName: 'replaceIdentifierWithFixedValueNotAssignedAtDeclarationTransform',
    transformEnabled: true,
    moduleName: 'replaceIdentifierWithFixedValueNotAssignedAtDeclaration',
  },
  {
    id: 'new-function-string-body',
    title: 'New Function String Body',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches `new Function(\"…\")()` with a single string body argument and no call arguments, replaceable with parsed code.',
    codeExample: [
      "const n = new Function('return 1')();",
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceNewFuncCallsWithLiteralContentMatch',
    transformName: 'replaceNewFuncCallsWithLiteralContentTransform',
    transformEnabled: true,
    moduleName: 'replaceNewFuncCallsWithLiteralContent',
  },
  {
    id: 'sequence-expression-split',
    title: 'Comma Sequence Expression Statements',
    categoryGroup: 'obfuscation',
    category: 'sequences',
    description: 'Matches expression statements whose expression is a comma sequence with multiple operands.',
    codeExample: [
      "log('a'), log('b'), 3;",
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceSequencesWithExpressionsMatch',
    transformName: 'replaceSequencesWithExpressionsTransform',
    transformEnabled: true,
    moduleName: 'replaceSequencesWithExpressions',
  },
  {
    id: 'function-constructor-literals',
    title: 'Function Constructor Literals',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches `Function.constructor(...)` calls whose arguments are all literals.',
    codeExample: [
      "const f = Function.constructor('return 1');",
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveFunctionConstructorCallsMatch',
    transformName: 'resolveFunctionConstructorCallsTransform',
    transformEnabled: true,
    moduleName: 'resolveFunctionConstructorCalls',
  },
  {
    id: 'array-index-member-resolution',
    title: 'Large Array Literal Index Reads',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches large array table initializers (length threshold) whose numeric index reads can be resolved to elements.',
    codeExample: [
      '// Array literal length must exceed REstringer threshold (20+ elements).',
      'const t = [/* …21 elements… */];',
      'return t[0];',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveMemberExpressionReferencesToArrayIndexMatch',
    transformName: 'resolveMemberExpressionReferencesToArrayIndexTransform',
    transformEnabled: true,
    moduleName: 'resolveMemberExpressionReferencesToArrayIndex',
  },
  {
    id: 'member-direct-literal-assignment',
    title: 'Literal Member Assignments',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches member assignments to literals where other reads of the same property can be replaced safely.',
    codeExample: [
      'function f() {',
      '  const o = {};',
      '  o.x = 1;',
      '  return o.x;',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveMemberExpressionsWithDirectAssignmentMatch',
    transformName: 'resolveMemberExpressionsWithDirectAssignmentTransform',
    transformEnabled: true,
    moduleName: 'resolveMemberExpressionsWithDirectAssignment',
  },
  {
    id: 'if-redundant-logical',
    title: 'If Tests With Redundant Logical Operands',
    categoryGroup: 'obfuscation',
    category: 'conditionals',
    description: 'Matches `if` tests that are logical expressions with a deterministically truthy or falsy operand.',
    codeExample: [
      'if ([] && sideEffect()) {',
      '  run();',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveRedundantLogicalExpressionsMatch',
    transformName: 'resolveRedundantLogicalExpressionsTransform',
    transformEnabled: true,
    moduleName: 'resolveRedundantLogicalExpressions',
  },
  {
    id: 'chained-declarators',
    title: 'Chained Declarators',
    categoryGroup: 'obfuscation',
    category: 'variables',
    description: 'Matches `var`/`let`/`const` declarations with multiple declarators that can be split into separate declarations.',
    codeExample: [
      'const a = 1, b = 2;',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'separateChainedDeclaratorsMatch',
    transformName: 'separateChainedDeclaratorsTransform',
    transformEnabled: true,
    moduleName: 'separateChainedDeclarators',
  },
  {
    id: 'if-empty-branch-prune',
    title: 'Empty If Statements',
    categoryGroup: 'obfuscation',
    category: 'conditionals',
    description: 'Matches `if` statements with empty consequent, empty alternate, or both, eligible for structural simplification.',
    codeExample: [
      'if (cond) {',
      '  work();',
      '} else {',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'simplifyIfStatementsMatch',
    transformName: 'simplifyIfStatementsTransform',
    transformEnabled: true,
    moduleName: 'simplifyIfStatements',
  },
  {
    id: 'function-apply-shells',
    title: 'Inner Function Apply Wrappers',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches functions that only return an inner function invoked with `.apply(this, arguments)`.',
    codeExample: [
      'function outer() {',
      '  return function inner() {',
      '    return 1;',
      '  }.apply(this, arguments);',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'unwrapFunctionShellsMatch',
    transformName: 'unwrapFunctionShellsTransform',
    transformEnabled: true,
    moduleName: 'unwrapFunctionShells',
  },
  {
    id: 'simple-op-wrapper-calls',
    title: 'Single-Return Operation Wrappers',
    categoryGroup: 'obfuscation',
    category: 'calls',
    description: 'Matches trivial wrappers around binary, logical, unary, or update operations that can be expressed as direct operations on call arguments.',
    codeExample: [
      'function add(a, b) {',
      '  return a + b;',
      '}',
      'add(1, 2);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'unwrapSimpleOperationsMatch',
    transformName: 'unwrapSimpleOperationsTransform',
    transformEnabled: true,
    moduleName: 'unwrapSimpleOperations',
  },
]);

export const knownStructureIds = Object.freeze(
  knownStructureRegistry.map((structure) => structure.id),
);
