export const knownStructureRegistry = Object.freeze([
  {
    id: 'proxy-calls',
    title: 'Proxy Calls',
    categoryGroup: 'obfuscation',
    category: 'calls',
    description: 'Matches function declarations whose only statement returns a call, the callee is an identifier, and every parameter is passed through as the same-named argument in order.',
    codeExample: [
      'function proxyCall(a, b) {',
      '  return sum(a, b);',
      '}',
      '',
      'const sum = (left, right) => left + right;',
      'const total = proxyCall(2, 3);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveProxyCallsMatch',
    transformName: 'resolveProxyCallsTransform',
    transformEnabled: true,
    moduleName: 'resolveProxyCalls',
  },
  {
    id: 'proxy-variables',
    title: 'Proxy Variables',
    categoryGroup: 'obfuscation',
    category: 'variables',
    description: 'Matches variable declarators whose initializer is another identifier (simple alias), subject to modification and scope checks.',
    codeExample: [
      'const originalValue = computeScore(input);',
      'const aliasedValue = originalValue;',
      '',
      'console.log(aliasedValue);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveProxyVariablesMatch',
    transformName: 'resolveProxyVariablesTransform',
    transformEnabled: true,
    moduleName: 'resolveProxyVariables',
  },
  {
    id: 'proxy-references',
    title: 'Proxy References',
    categoryGroup: 'obfuscation',
    category: 'variables',
    description: 'Matches variable declarators whose initializer is an identifier or member expression (indirection), subject to replacement-safety and modification checks.',
    codeExample: [
      'const state = {',
      "  token: 'abc123',",
      '};',
      '',
      'const tokenRef = state.token;',
      'useToken(tokenRef);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveProxyReferencesMatch',
    transformName: 'resolveProxyReferencesTransform',
    transformEnabled: true,
    moduleName: 'resolveProxyReferences',
  },
  {
    id: 'wrapped-value-shells',
    title: 'Wrapped Value Shells',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches function declarations whose body is a single `return` whose argument is a literal or an identifier.',
    codeExample: [
      'function revealValue() {',
      "  return 'decoded';",
      '}',
      '',
      'const message = revealValue();',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceFunctionShellsWithWrappedValueMatch',
    transformName: 'replaceFunctionShellsWithWrappedValueTransform',
    transformEnabled: true,
    moduleName: 'replaceFunctionShellsWithWrappedValue',
  },
  {
    id: 'iife-wrappers',
    title: 'IIFE Wrappers',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches zero-argument immediately invoked function expressions (or similar call sites) that the unwrapper recognizes as structurally unwrappable.',
    codeExample: [
      'const config = (function () {',
      '  return {retries: 3};',
      '}());',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'unwrapIIFEsMatch',
    transformName: 'unwrapIIFEsTransform',
    transformEnabled: true,
    moduleName: 'unwrapIIFEs',
  },
  {
    id: 'template-literal-strings',
    title: 'Template Literal Strings',
    categoryGroup: 'obfuscation',
    category: 'literals',
    description: 'Matches template literals whose interpolated expressions are all literals (including templates with no interpolations).',
    codeExample: [
      'const label = `debug mode enabled`;',
      'console.log(label);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'parseTemplateLiteralsIntoStringLiteralsMatch',
    transformName: 'parseTemplateLiteralsIntoStringLiteralsTransform',
    transformEnabled: true,
    moduleName: 'parseTemplateLiteralsIntoStringLiterals',
  },
  {
    id: 'fixed-assigned-values',
    title: 'Fixed Assigned Values',
    categoryGroup: 'obfuscation',
    category: 'variables',
    description: 'Matches identifier references whose binding is declared with a literal initializer and is not treated as modified by the AST.',
    codeExample: [
      'const statusCode = 200;',
      '',
      'if (statusCode === 200) {',
      "  console.log('ok');",
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceIdentifierWithFixedAssignedValueMatch',
    transformName: 'replaceIdentifierWithFixedAssignedValueTransform',
    transformEnabled: true,
    moduleName: 'replaceIdentifierWithFixedAssignedValue',
  },
  {
    id: 'deterministic-if-statements',
    title: 'Deterministic If Statements',
    categoryGroup: 'obfuscation',
    category: 'conditionals',
    description: 'Matches `if` statements whose test is a literal or a unary operator applied to a literal (e.g. `true`, `0`, `-1`).',
    codeExample: [
      'if (true) {',
      '  runVisibleBranch();',
      '} else {',
      '  runDeadBranch();',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveDeterministicIfStatementsMatch',
    transformName: 'resolveDeterministicIfStatementsTransform',
    transformEnabled: true,
    moduleName: 'resolveDeterministicIfStatements',
  },
  {
    id: 'sequence-rearrangement',
    title: 'Rearrange Sequences',
    categoryGroup: 'obfuscation',
    category: 'sequences',
    description: 'Matches `return` statements whose argument is a comma (`SequenceExpression`) with multiple operands, and `if` statements whose test is a comma expression with multiple operands.',
    codeExample: [
      'function viaReturn() {',
      '  return (1, 2, 3);',
      '}',
      '',
      'if ((0, true)) {',
      '  run();',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'rearrangeSequencesMatch',
    transformName: 'rearrangeSequencesTransform',
    transformEnabled: true,
    moduleName: 'rearrangeSequences',
  },
  {
    id: 'switch-rearrangement',
    title: 'Rearrange Switches',
    categoryGroup: 'obfuscation',
    category: 'control-flow',
    description: 'Matches `switch` statements whose discriminant is an identifier declared with a literal initializer (used for control flow flattening).',
    codeExample: [
      "let mode = 'init';",
      'switch (mode) {',
      "  case 'init':",
      "    mode = 'ready';",
      '    break;',
      "  case 'ready':",
      '    render();',
      '    break;',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'rearrangeSwitchesMatch',
    transformName: 'rearrangeSwitchesTransform',
    transformEnabled: false,
    moduleName: 'rearrangeSwitches',
  },
  {
    id: 'computed-members',
    title: 'Computed Members',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches computed `obj[\'prop\']` member reads with a string literal key, computed method names with literal keys, and object literal properties whose key is a string literal that forms a valid identifier.',
    codeExample: [
      'const user = {name: "Ada"};',
      '',
      "console.log(user['name']);",
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'normalizeComputedMatch',
    transformName: 'normalizeComputedTransform',
    transformEnabled: true,
    moduleName: 'normalizeComputed',
  },
  {
    id: 'simplify-calls',
    title: 'Simplify Calls',
    categoryGroup: 'obfuscation',
    category: 'calls',
    description: 'Matches member calls where the property is `call` or `apply`, the first argument is `this` or an allowed literal, and the callee is not a function expression (per REstringer’s simplify-calls rules).',
    codeExample: [
      'function host() {',
      '  function f() {}',
      '',
      '  f.call(this, 1);',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'simplifyCallsMatch',
    transformName: 'simplifyCallsTransform',
    transformEnabled: true,
    moduleName: 'simplifyCalls',
  },
  {
    id: 'empty-statements',
    title: 'Empty Statements',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches empty statements (`;`) that aren\'t the required body of `if`/`for`/`while`/`do` constructs.',
    codeExample: [
      'function example() {',
      '  ;',
      '  return 1;',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'normalizeEmptyStatementsMatch',
    transformName: 'normalizeEmptyStatementsTransform',
    transformEnabled: true,
    moduleName: 'normalizeEmptyStatements',
  },
  {
    id: 'dead-node-declarations',
    title: 'Dead Code',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches binding identifiers (e.g. in `const`/`let`/`var`, functions, or classes) under a non-program parent that have no recorded references (may miss dynamic use such as `eval` or bracketed property access).',
    codeExample: [
      'function outer() {',
      '  const neverRead = 1;',
      '  return 2;',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'removeDeadNodesMatch',
    transformName: 'removeDeadNodesTransform',
    transformEnabled: true,
    moduleName: 'removeDeadNodes',
  },
  {
    id: 'redundant-block-statements',
    title: 'Redundant Block Statements',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches block statements that are direct children of another block or of the program body (nested `{` … `}` wrappers).',
    codeExample: [
      '(function () {',
      '  {',
      '    {',
      '      console.log(1);',
      '    }',
      '  }',
      '}());',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'removeRedundantBlockStatementsMatch',
    transformName: 'removeRedundantBlockStatementsTransform',
    transformEnabled: true,
    moduleName: 'removeRedundantBlockStatements',
  },
  {
    id: 'logical-expressions-as-if',
    title: 'Logical Expressions as If',
    categoryGroup: 'obfuscation',
    category: 'conditionals',
    description: 'Matches expression statements whose expression is a logical `&&` or `||` at the top level (candidates for rewriting to explicit `if`).',
    codeExample: [
      'const ready = true;',
      'ready && launch();',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceBooleanExpressionsWithIfMatch',
    transformName: 'replaceBooleanExpressionsWithIfTransform',
    transformEnabled: true,
    moduleName: 'replaceBooleanExpressionsWithIf',
  },
  {
    id: 'call-unwrapped-identifier',
    title: 'Call Unwrapped Identifier',
    categoryGroup: 'obfuscation',
    category: 'calls',
    description: 'Matches call expressions whose callee is a function declaration or a `const`/`let`/`var` function expression; the transform only applies when that function’s body is a single `return` of an identifier or a zero-argument call.',
    codeExample: [
      'const value = 1;',
      'function id() {',
      '  return value;',
      '}',
      'id();',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceCallExpressionsWithUnwrappedIdentifierMatch',
    transformName: 'replaceCallExpressionsWithUnwrappedIdentifierTransform',
    transformEnabled: true,
    moduleName: 'replaceCallExpressionsWithUnwrappedIdentifier',
  },
  {
    id: 'eval-string-literals',
    title: 'Eval String Literals',
    categoryGroup: 'obfuscation',
    category: 'literals',
    description: 'Matches `eval(...)` call expressions whose first argument is a string literal (the transform parses that string into AST nodes without running `eval`).',
    codeExample: [
      "const n = eval('40 + 2');",
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceEvalCallsWithLiteralContentMatch',
    transformName: 'replaceEvalCallsWithLiteralContentTransform',
    transformEnabled: true,
    moduleName: 'replaceEvalCallsWithLiteralContent',
  },
  {
    id: 'iife-literal-shells',
    title: 'IIFE Literal Shells',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches anonymous function expressions used as the callee of a zero-argument call, with a single `return` of a literal or identifier.',
    codeExample: [
      'const boxed = (function () {',
      '  return 7;',
      '}());',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceFunctionShellsWithWrappedValueIIFEMatch',
    transformName: 'replaceFunctionShellsWithWrappedValueIIFETransform',
    transformEnabled: true,
    moduleName: 'replaceFunctionShellsWithWrappedValueIIFE',
  },
  {
    id: 'fixed-value-after-declaration',
    title: 'Fixed Value After Declaration',
    categoryGroup: 'obfuscation',
    category: 'variables',
    description: 'Matches the binding identifier of a `let`/`var`/`const` declarator with no initializer when it has exactly one assignment from a literal and passes safety checks.',
    codeExample: [
      'function f() {',
      '  let v;',
      '  v = 3;',
      '  return v;',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceIdentifierWithFixedValueNotAssignedAtDeclarationMatch',
    transformName: 'replaceIdentifierWithFixedValueNotAssignedAtDeclarationTransform',
    transformEnabled: true,
    moduleName: 'replaceIdentifierWithFixedValueNotAssignedAtDeclaration',
  },
  {
    id: 'new-function-string-body',
    title: 'New Function String Body',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches `new Function(<string>)()` patterns: `Function` callee, exactly one string-literal argument, used as the callee of an immediately invoked call with no further arguments.',
    codeExample: [
      "const n = new Function('return 1')();",
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceNewFuncCallsWithLiteralContentMatch',
    transformName: 'replaceNewFuncCallsWithLiteralContentTransform',
    transformEnabled: true,
    moduleName: 'replaceNewFuncCallsWithLiteralContent',
  },
  {
    id: 'sequence-expression-split',
    title: 'Replace Sequences With Expressions',
    categoryGroup: 'obfuscation',
    category: 'sequences',
    description: 'Matches expression statements whose expression is a `SequenceExpression` (comma operator) with more than one operand.',
    codeExample: [
      '1, 2, 3;',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'replaceSequencesWithExpressionsMatch',
    transformName: 'replaceSequencesWithExpressionsTransform',
    transformEnabled: true,
    moduleName: 'replaceSequencesWithExpressions',
  },
  {
    id: 'function-constructor-literals',
    title: 'Function Constructor Literals',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches `Function.constructor(...)` calls whose arguments are all literals.',
    codeExample: [
      "const f = Function.constructor('return 1');",
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveFunctionConstructorCallsMatch',
    transformName: 'resolveFunctionConstructorCallsTransform',
    transformEnabled: true,
    moduleName: 'resolveFunctionConstructorCalls',
  },
  {
    id: 'array-index-member-resolution',
    title: 'Array Index Member Resolution',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches variable declarators initialized to an array literal longer than REstringer’s threshold (numeric index reads on that binding are handled by the transform).',
    codeExample: [
      'const t = [',
      '  0, 1, 2, 3, 4, 5, 6, 7, 8, 9,',
      '  10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,',
      '];',
      '',
      'function readTable() {',
      '  return t[3];',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveMemberExpressionReferencesToArrayIndexMatch',
    transformName: 'resolveMemberExpressionReferencesToArrayIndexTransform',
    transformEnabled: true,
    moduleName: 'resolveMemberExpressionReferencesToArrayIndex',
  },
  {
    id: 'member-direct-literal-assignment',
    title: 'Member Direct Literal Assignment',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches member expressions on the left of an assignment to a literal when the object binding has other reads of the same property that the transform can fold (subject to modification checks).',
    codeExample: [
      'function f() {',
      '  const o = {};',
      '  o.x = 1;',
      '  return o.x;',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveMemberExpressionsWithDirectAssignmentMatch',
    transformName: 'resolveMemberExpressionsWithDirectAssignmentTransform',
    transformEnabled: true,
    moduleName: 'resolveMemberExpressionsWithDirectAssignment',
  },
  {
    id: 'if-redundant-logical',
    title: 'If Redundant Logical',
    categoryGroup: 'obfuscation',
    category: 'conditionals',
    description: 'Matches `if` statements whose test is a logical `&&` or `||` where at least one operand has statically known truthiness so the test can be simplified.',
    codeExample: [
      'if ([] && sideEffect()) {',
      '  run();',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveRedundantLogicalExpressionsMatch',
    transformName: 'resolveRedundantLogicalExpressionsTransform',
    transformEnabled: true,
    moduleName: 'resolveRedundantLogicalExpressions',
  },
  {
    id: 'chained-declarators',
    title: 'Chained Declarators',
    categoryGroup: 'obfuscation',
    category: 'variables',
    description: 'Matches `var`/`let`/`const` declarations that declare more than one binding in a single statement.',
    codeExample: [
      'const a = 1, b = 2;',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'separateChainedDeclaratorsMatch',
    transformName: 'separateChainedDeclaratorsTransform',
    transformEnabled: true,
    moduleName: 'separateChainedDeclarators',
  },
  {
    id: 'if-empty-branch-prune',
    title: 'Empty If Statements',
    categoryGroup: 'obfuscation',
    category: 'conditionals',
    description: 'Matches `if` statements with an empty consequent, an empty `else`, or both (empty block or empty statement counts as empty).',
    codeExample: [
      'if (cond) {',
      '  work();',
      '} else {',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'simplifyIfStatementsMatch',
    transformName: 'simplifyIfStatementsTransform',
    transformEnabled: true,
    moduleName: 'simplifyIfStatements',
  },
  {
    id: 'function-apply-shells',
    title: 'Function Apply Shells',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches function declarations or expressions whose body is a single `return` of a call to `.apply` on an inner *function expression*, with exactly two arguments (`this` and `arguments`).',
    codeExample: [
      'function outer() {',
      '  return function inner() {',
      '    return 1;',
      '  }.apply(this, arguments);',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'unwrapFunctionShellsMatch',
    transformName: 'unwrapFunctionShellsTransform',
    transformEnabled: true,
    moduleName: 'unwrapFunctionShells',
  },
  {
    id: 'simple-op-wrapper-calls',
    title: 'Simple Operation Wrapper Calls',
    categoryGroup: 'obfuscation',
    category: 'calls',
    description: 'Matches binary, logical, unary, or update expressions that are the only `return` in a function and use parameters as operands (call sites of that function are updated by the transform).',
    codeExample: [
      'function add(a, b) {',
      '  return a + b;',
      '}',
      'add(1, 2);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'unwrapSimpleOperationsMatch',
    transformName: 'unwrapSimpleOperationsTransform',
    transformEnabled: true,
    moduleName: 'unwrapSimpleOperations',
  },
  {
    id: 'inline-operator-objects',
    title: 'Inline Operator Objects',
    categoryGroup: 'obfuscation',
    category: 'wrappers',
    description: 'Matches variable declarators whose initializer is a readonly object of literal properties or single-return operator/call shells, then used only as member reads or call sites.',
    codeExample: [
      'const ops = {',
      '  add: function (a, b) {',
      '    return a + b;',
      '  },',
      "  msg: 'ok',",
      '};',
      '',
      'ops.add(1, 2);',
      'console.log(ops.msg);',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'inlineOperatorObjectsMatch',
    transformName: 'inlineOperatorObjectsTransform',
    transformEnabled: true,
    moduleName: 'inlineOperatorObjects',
  },
  {
    id: 'redundant-not-operators',
    title: 'Redundant Not Operators',
    categoryGroup: 'obfuscation',
    category: 'cleanup',
    description: 'Matches unary `!` expressions whose argument is a foldable literal, array, object, template, or nested unary, so the boolean result can be substituted.',
    codeExample: [
      'const flag = !true;',
      'const empty = !0;',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'normalizeRedundantNotOperatorMatch',
    transformName: 'normalizeRedundantNotOperatorTransform',
    transformEnabled: true,
    moduleName: 'normalizeRedundantNotOperator',
  },
  {
    id: 'definite-member-expressions',
    title: 'Definite Member Expressions',
    categoryGroup: 'obfuscation',
    category: 'literals',
    description: 'Matches member expressions that read a literal index or `.length` from a string or array literal, such as `\'abc\'[0]` or `[1, 2][0]`.',
    codeExample: [
      "const first = 'hello'[0];",
      "const len = 'hello'.length;",
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveDefiniteMemberExpressionsMatch',
    transformName: 'resolveDefiniteMemberExpressionsTransform',
    transformEnabled: true,
    moduleName: 'resolveDefiniteMemberExpressions',
  },
  {
    id: 'deterministic-ternaries',
    title: 'Deterministic Ternaries',
    categoryGroup: 'obfuscation',
    category: 'conditionals',
    description: 'Matches conditional (ternary) expressions whose test is a foldable literal, so the consequent or alternate can replace the whole expression.',
    codeExample: [
      "const value = true ? 'yes' : 'no';",
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveDeterministicConditionalExpressionsMatch',
    transformName: 'resolveDeterministicConditionalExpressionsTransform',
    transformEnabled: true,
    moduleName: 'resolveDeterministicConditionalExpressions',
  },
  {
    id: 'deterministic-while-statements',
    title: 'Deterministic While Statements',
    categoryGroup: 'obfuscation',
    category: 'control-flow',
    description: 'Matches `while` / `do-while` statements whose test is a foldable literal, so a falsy loop can be removed (do-while keeps the body once).',
    codeExample: [
      'while (false) {',
      '  never();',
      '}',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveDeterministicWhileStatementsMatch',
    transformName: 'resolveDeterministicWhileStatementsTransform',
    transformEnabled: true,
    moduleName: 'resolveDeterministicWhileStatements',
  },
  {
    id: 'minimal-alphabet',
    title: 'Minimal Alphabet',
    categoryGroup: 'obfuscation',
    category: 'literals',
    description: 'Matches JSFuck-style unary coercions and `+` concatenations on non-numeric literals and arrays, such as `+true`, `+[]`, or `[] + []`.',
    codeExample: [
      'const n = +true;',
      'const s = [] + [];',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveMinimalAlphabetMatch',
    transformName: 'resolveMinimalAlphabetTransform',
    transformEnabled: true,
    moduleName: 'resolveMinimalAlphabet',
  },
  {
    id: 'nested-binary-expressions',
    title: 'Nested Binary Expressions',
    categoryGroup: 'obfuscation',
    category: 'literals',
    description: 'Matches root binary-expression trees that can be folded or flattened because some or all operands are literals (for example `1 + 2 * 2`).',
    codeExample: [
      'const n = 1 + 2 * 2;',
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolveNestedBinaryExpressionsMatch',
    transformName: 'resolveNestedBinaryExpressionsTransform',
    transformEnabled: true,
    moduleName: 'resolveNestedBinaryExpressions',
  },
  {
    id: 'pure-literal-method-calls',
    title: 'Pure Literal Method Calls',
    categoryGroup: 'obfuscation',
    category: 'calls',
    description: 'Matches allow-listed pure method calls on string or array literals, such as `\'a,b\'.split(\',\')` or `[1, 2].join(\'\')`, with no callbacks.',
    codeExample: [
      "const parts = 'a,b'.split(',');",
    ].join('\n'),
    noEval: true,
    executionMode: 'no-eval',
    matcherName: 'resolvePureLiteralMethodCallsMatch',
    transformName: 'resolvePureLiteralMethodCallsTransform',
    transformEnabled: true,
    moduleName: 'resolvePureLiteralMethodCalls',
  },
]);

export const knownStructureIds = Object.freeze(
  knownStructureRegistry.map((structure) => structure.id),
);
