export const knownStructureRegistry = Object.freeze([
  {
    id: 'proxy-calls',
    title: 'Proxy Calls',
    category: 'calls',
    description: 'Matches wrapper functions that only forward arguments into another call.',
    tags: Object.freeze(['proxy', 'call', 'wrapper', 'structural']),
    searchTerms: Object.freeze(['forwarder', 'pass-through', 'indirection']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: true,
    matcherName: 'resolveProxyCallsMatch',
    transformName: 'resolveProxyCallsTransform',
    transformEnabled: true,
    moduleName: 'resolveProxyCalls',
  },
  {
    id: 'proxy-variables',
    title: 'Proxy Variables',
    category: 'variables',
    description: 'Matches identifier aliases that point directly at another identifier.',
    tags: Object.freeze(['proxy', 'variable', 'alias', 'structural']),
    searchTerms: Object.freeze(['redirect', 'reference', 'aliasing']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: true,
    matcherName: 'resolveProxyVariablesMatch',
    transformName: 'resolveProxyVariablesTransform',
    transformEnabled: true,
    moduleName: 'resolveProxyVariables',
  },
  {
    id: 'proxy-references',
    title: 'Proxy References',
    category: 'variables',
    description: 'Matches proxy declarations that redirect reads to another identifier or member expression.',
    tags: Object.freeze(['proxy', 'reference', 'variable', 'structural']),
    searchTerms: Object.freeze(['redirect', 'indirection', 'lookup']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: true,
    matcherName: 'resolveProxyReferencesMatch',
    transformName: 'resolveProxyReferencesTransform',
    transformEnabled: true,
    moduleName: 'resolveProxyReferences',
  },
  {
    id: 'wrapped-value-shells',
    title: 'Wrapped Value Shells',
    category: 'wrappers',
    description: 'Matches function shells whose only job is to return a wrapped value.',
    tags: Object.freeze(['wrapper', 'function', 'value', 'leaf']),
    searchTerms: Object.freeze(['shell', 'wrapper-return', 'encapsulation']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: true,
    matcherName: 'replaceFunctionShellsWithWrappedValueMatch',
    transformName: 'replaceFunctionShellsWithWrappedValueTransform',
    transformEnabled: true,
    moduleName: 'replaceFunctionShellsWithWrappedValue',
  },
  {
    id: 'iife-wrappers',
    title: 'IIFE Wrappers',
    category: 'wrappers',
    description: 'Matches immediately invoked wrapper functions that can be unwrapped structurally.',
    tags: Object.freeze(['iife', 'wrapper', 'cleanup', 'structural']),
    searchTerms: Object.freeze(['self-invoking', 'immediate', 'unwrap']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: true,
    matcherName: 'unwrapIIFEsMatch',
    transformName: 'unwrapIIFEsTransform',
    transformEnabled: true,
    moduleName: 'unwrapIIFEs',
  },
  {
    id: 'template-literal-strings',
    title: 'Template Literal Strings',
    category: 'literals',
    description: 'Matches template literals made entirely from static literal content.',
    tags: Object.freeze(['template', 'literal', 'string', 'cleanup']),
    searchTerms: Object.freeze(['backtick', 'string folding', 'static']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: true,
    matcherName: 'parseTemplateLiteralsIntoStringLiteralsMatch',
    transformName: 'parseTemplateLiteralsIntoStringLiteralsTransform',
    transformEnabled: true,
    moduleName: 'parseTemplateLiteralsIntoStringLiterals',
  },
  {
    id: 'fixed-assigned-values',
    title: 'Fixed Assigned Values',
    category: 'variables',
    description: 'Matches identifiers assigned a fixed value that can be propagated safely.',
    tags: Object.freeze(['variable', 'constant', 'assignment', 'structural']),
    searchTerms: Object.freeze(['constant propagation', 'fixed value', 'replacement']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: true,
    matcherName: 'replaceIdentifierWithFixedAssignedValueMatch',
    transformName: 'replaceIdentifierWithFixedAssignedValueTransform',
    transformEnabled: true,
    moduleName: 'replaceIdentifierWithFixedAssignedValue',
  },
  {
    id: 'deterministic-if-statements',
    title: 'Deterministic If Statements',
    category: 'conditionals',
    description: 'Matches `if` statements whose branch outcome is statically determined.',
    tags: Object.freeze(['conditional', 'if', 'cleanup', 'control-flow']),
    searchTerms: Object.freeze(['branch folding', 'dead branch', 'deterministic']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: true,
    matcherName: 'resolveDeterministicIfStatementsMatch',
    transformName: 'resolveDeterministicIfStatementsTransform',
    transformEnabled: true,
    moduleName: 'resolveDeterministicIfStatements',
  },
  {
    id: 'sequence-rearrangement',
    title: 'Sequence Rearrangement',
    category: 'sequences',
    description: 'Matches sequence expressions that can be expanded into a clearer execution order.',
    tags: Object.freeze(['sequence', 'expression', 'cleanup', 'structural']),
    searchTerms: Object.freeze(['comma operator', 'ordering', 'rearrange']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: false,
    matcherName: 'rearrangeSequencesMatch',
    transformName: 'rearrangeSequencesTransform',
    transformEnabled: true,
    moduleName: 'rearrangeSequences',
  },
  {
    id: 'switch-rearrangement',
    title: 'Switch Rearrangement',
    category: 'control-flow',
    description: 'Matches switch statements whose case order can be rearranged into a more direct flow.',
    tags: Object.freeze(['switch', 'control-flow', 'cleanup', 'structural']),
    searchTerms: Object.freeze(['dispatcher', 'case order', 'flow flattening']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: false,
    matcherName: 'rearrangeSwitchesMatch',
    transformName: 'rearrangeSwitchesTransform',
    transformEnabled: false,
    moduleName: 'rearrangeSwitches',
  },
  {
    id: 'computed-members',
    title: 'Computed Members',
    category: 'cleanup',
    description: 'Matches computed member access and property keys that can be normalized to identifier syntax.',
    tags: Object.freeze(['member-expression', 'property', 'syntax', 'cleanup']),
    searchTerms: Object.freeze(['dot notation', 'bracket notation', 'normalization']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: true,
    matcherName: 'normalizeComputedMatch',
    transformName: 'normalizeComputedTransform',
    transformEnabled: true,
    moduleName: 'normalizeComputed',
  },
  {
    id: 'simplify-calls',
    title: 'Simplify Calls',
    category: 'calls',
    description: 'Matches call expressions that can be simplified without executing code.',
    tags: Object.freeze(['call', 'cleanup', 'expression', 'structural']),
    searchTerms: Object.freeze(['call folding', 'argument cleanup', 'simplification']),
    browserSafe: true,
    experimental: false,
    enabledByDefault: true,
    matcherName: 'simplifyCallsMatch',
    transformName: 'simplifyCallsTransform',
    transformEnabled: true,
    moduleName: 'simplifyCalls',
  },
]);

export const knownStructureIds = Object.freeze(
  knownStructureRegistry.map((structure) => structure.id),
);
