/**
 * Serializes an enriched report envelope into a self-contained HTML document.
 * No external CSS, JS, or asset dependencies — the output is a single file.
 *
 * @param {object} envelope  report envelope (without _store, already enriched)
 * @returns {string}  complete HTML document
 */
export function formatReportHtml(envelope) {
  const {meta, totalFindings, sections} = envelope;
  const title = `flASTer — ${meta.input.label}`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
${CSS}
</style>
</head>
<body>
<header>
  <h1>flASTer Report</h1>
  <dl class="meta">
    <dt>Input</dt><dd class="mono">${esc(meta.input.label)}</dd>
    <dt>Analyzed</dt><dd>${esc(meta.analyzedAt)}</dd>
    <dt>flASTer version</dt><dd>${esc(meta.flasterVersion ?? '—')}</dd>
    <dt>Findings</dt><dd>${totalFindings}</dd>
    ${meta.report.fullDetail ? '<dt>Detail</dt><dd>Full</dd>' : ''}
  </dl>
</header>
<main>
${totalFindings === 0 ? '<p class="no-findings">No findings.</p>' : sections.map(renderSection).join('\n')}
</main>
<footer>
  <p>Generated by <strong>flASTer</strong> ${esc(meta.flasterVersion ?? '')} &mdash; ${esc(meta.analyzedAt)}</p>
</footer>
</body>
</html>`;
}

function renderSection(section) {
  return `<section class="report-section" id="section-${esc(section.id)}">
  <h2>${esc(section.title)}</h2>
  <p class="helper">${esc(section.helperCopy)}</p>
  <div class="findings">
${section.findings.map(renderFinding).join('\n')}
  </div>
</section>`;
}

function renderFinding(finding) {
  if (finding.kind === 'capability') {
    return renderCapabilityFinding(finding);
  }
  return renderStructureFinding(finding);
}

function renderStructureFinding(finding) {
  const badge = finding.category
    ? `<span class="badge">${esc(finding.category)}</span>`
    : '';

  const description = finding.description
    ? `<p class="description">${esc(finding.description)}</p>`
    : '';

  const extractions = finding.extractions?.length
    ? `<div class="extractions"><strong>Extractions</strong>${renderExtractions(finding.extractions)}</div>`
    : '';

  return `    <article class="finding kind-structure">
      <header class="finding-header">
        <h3>${esc(finding.title)} ${badge}</h3>
        <span class="match-count">${finding.matchCount} match${finding.matchCount === 1 ? '' : 'es'}</span>
      </header>
      ${description}
      ${extractions}
      ${renderEvidenceTable(finding.evidence)}
    </article>`;
}

function renderCapabilityFinding(finding) {
  const riskClass = `risk-${(finding.risk ?? 'unknown').toLowerCase().replace(/\s+/g, '-')}`;

  const description = finding.description
    ? `<p class="description">${esc(finding.description)}</p>`
    : '';

  const riskReason = finding.riskReason
    ? `<p class="risk-reason"><strong>Risk:</strong> ${esc(finding.riskReason)}</p>`
    : '';

  const detectors = finding.firedDetectorIds?.length
    ? `<p class="fired-detectors"><strong>Detectors:</strong> ${finding.firedDetectorIds.map((id) => `<code>${esc(id)}</code>`).join(', ')}</p>`
    : '';

  return `    <article class="finding kind-capability ${riskClass}">
      <header class="finding-header">
        <h3>${esc(finding.title)}</h3>
        <span class="risk-badge ${riskClass}">${esc(finding.risk ?? 'unknown')}</span>
        <span class="match-count">${finding.matchCount} evidence match${finding.matchCount === 1 ? '' : 'es'}</span>
      </header>
      ${description}
      ${riskReason}
      ${detectors}
      ${renderEvidenceTable(finding.evidence)}
    </article>`;
}

/**
 * @param {object[]} evidence
 */
function renderEvidenceTable(evidence) {
  if (!evidence?.length) {
    return '<p class="no-evidence">No evidence locations.</p>';
  }

  const hasSnippet  = evidence.some((e) => e.snippet !== null && e.snippet !== undefined);
  const hasDetector = evidence.some((e) => e.detectorId !== null && e.detectorId !== undefined);

  const extraCols = [
    hasDetector ? '<th>Detector</th>' : '',
    hasSnippet  ? '<th>Snippet</th>'  : '',
  ].join('');

  const rows = evidence.map((e) => {
    const loc = `${e.line}:${e.column}`;
    const endLoc = (e.endLine !== e.line || e.endColumn !== e.column)
      ? ` – ${e.endLine}:${e.endColumn}`
      : '';
    const offsets = `${e.charStart}–${e.charEnd}`;

    const detectorCell = hasDetector
      ? `<td>${e.detectorId ? `<code>${esc(e.detectorId)}</code>` : ''}</td>`
      : '';
    const snippetCell = hasSnippet
      ? `<td>${e.snippet !== null && e.snippet !== undefined ? `<pre class="snippet">${esc(String(e.snippet))}</pre>` : ''}</td>`
      : '';

    return `        <tr>
          <td class="loc mono">${esc(loc)}${esc(endLoc)}</td>
          <td class="offsets mono">${esc(offsets)}</td>
          ${detectorCell}${snippetCell}
        </tr>`;
  }).join('\n');

  return `      <details class="evidence" open>
        <summary>Evidence (${evidence.length})</summary>
        <table>
          <thead><tr><th>Location</th><th>Offsets</th>${extraCols}</tr></thead>
          <tbody>
${rows}
          </tbody>
        </table>
      </details>`;
}

function renderExtractions(extractions) {
  return '<dl class="extraction-list">' +
    extractions.map((ex) =>
      `<dt>${esc(ex.role)}</dt><dd>${ex.values.map((v) => `<code>${esc(v)}</code>`).join(' ')}</dd>`,
    ).join('') +
    '</dl>';
}

/** HTML-escape a string value. */
function esc(value) {
  if (value === null || value === undefined) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const CSS = `
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root {
  --bg:          #0f1117;
  --surface:     #1a1d27;
  --surface2:    #22263a;
  --border:      #2e3248;
  --accent:      #5b8dee;
  --text:        #d4d8f0;
  --text-muted:  #6b728e;
  --code-bg:     #141824;
  --risk-high:   #e85c5c;
  --risk-medium: #e8a75c;
  --risk-low:    #5ce8a7;
  --risk-benign: #5b8dee;
  --radius:      6px;
  --font-sans:   system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  --font-mono:   ui-monospace, "Cascadia Code", "Fira Code", "Fira Mono", monospace;
}

html { font-size: 15px; }

body {
  font-family: var(--font-sans);
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  padding: 2rem 1rem;
  max-width: 1100px;
  margin: 0 auto;
}

a { color: var(--accent); }

/* ── Header ─────────────────────────────────────────────── */
header {
  border-bottom: 1px solid var(--border);
  padding-bottom: 1.5rem;
  margin-bottom: 2rem;
}

header h1 {
  font-size: 1.6rem;
  font-weight: 700;
  margin-bottom: 0.75rem;
  color: #fff;
}

dl.meta {
  display: grid;
  grid-template-columns: max-content 1fr;
  gap: 0.25rem 1rem;
  font-size: 0.9rem;
}

dl.meta dt {
  color: var(--text-muted);
  font-weight: 500;
}

/* ── Sections ───────────────────────────────────────────── */
.report-section {
  margin-bottom: 2.5rem;
}

.report-section h2 {
  font-size: 1.2rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--accent);
  margin-bottom: 0.35rem;
}

.helper {
  color: var(--text-muted);
  font-size: 0.875rem;
  margin-bottom: 1rem;
}

/* ── Findings ───────────────────────────────────────────── */
.findings {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.finding {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 1rem 1.25rem;
}

.finding-header {
  display: flex;
  align-items: baseline;
  gap: 0.75rem;
  flex-wrap: wrap;
  margin-bottom: 0.5rem;
}

.finding-header h3 {
  font-size: 1rem;
  font-weight: 600;
  color: #fff;
}

.match-count {
  font-size: 0.8rem;
  color: var(--text-muted);
  margin-left: auto;
  white-space: nowrap;
}

.description {
  font-size: 0.875rem;
  color: var(--text-muted);
  margin-bottom: 0.75rem;
}

/* ── Badge / Risk ───────────────────────────────────────── */
.badge {
  font-size: 0.72rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  padding: 0.15em 0.55em;
  border-radius: 99px;
  background: var(--surface2);
  color: var(--text-muted);
  border: 1px solid var(--border);
}

.risk-badge {
  font-size: 0.72rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  padding: 0.15em 0.55em;
  border-radius: 99px;
}

.risk-high   .risk-badge, .risk-badge.risk-high   { background: color-mix(in srgb, var(--risk-high) 15%, transparent); color: var(--risk-high); border: 1px solid var(--risk-high); }
.risk-medium .risk-badge, .risk-badge.risk-medium { background: color-mix(in srgb, var(--risk-medium) 15%, transparent); color: var(--risk-medium); border: 1px solid var(--risk-medium); }
.risk-low    .risk-badge, .risk-badge.risk-low    { background: color-mix(in srgb, var(--risk-low) 15%, transparent); color: var(--risk-low); border: 1px solid var(--risk-low); }
.risk-benign .risk-badge, .risk-badge.risk-benign { background: color-mix(in srgb, var(--risk-benign) 15%, transparent); color: var(--risk-benign); border: 1px solid var(--risk-benign); }

.kind-capability { border-left-width: 3px; }
.kind-capability.risk-high   { border-left-color: var(--risk-high); }
.kind-capability.risk-medium { border-left-color: var(--risk-medium); }
.kind-capability.risk-low    { border-left-color: var(--risk-low); }
.kind-capability.risk-benign { border-left-color: var(--risk-benign); }

/* ── Extractions ────────────────────────────────────────── */
.extractions {
  font-size: 0.875rem;
  margin-bottom: 0.75rem;
}

.extraction-list {
  display: grid;
  grid-template-columns: max-content 1fr;
  gap: 0.2rem 0.75rem;
  margin-top: 0.35rem;
}

.extraction-list dt {
  color: var(--text-muted);
  font-style: italic;
}

.fired-detectors, .risk-reason {
  font-size: 0.875rem;
  margin-bottom: 0.5rem;
}

/* ── Evidence ───────────────────────────────────────────── */
details.evidence {
  margin-top: 0.75rem;
}

details.evidence > summary {
  cursor: pointer;
  font-size: 0.85rem;
  font-weight: 600;
  color: var(--text-muted);
  user-select: none;
  list-style: none;
  display: flex;
  align-items: center;
  gap: 0.4rem;
  margin-bottom: 0.5rem;
}

details.evidence > summary::before {
  content: "▶";
  font-size: 0.65em;
  transition: transform 0.15s;
}

details[open].evidence > summary::before {
  transform: rotate(90deg);
}

table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.82rem;
}

th {
  text-align: left;
  color: var(--text-muted);
  font-weight: 600;
  font-size: 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  padding: 0.3rem 0.6rem;
  border-bottom: 1px solid var(--border);
}

td {
  padding: 0.3rem 0.6rem;
  border-bottom: 1px solid color-mix(in srgb, var(--border) 50%, transparent);
  vertical-align: top;
}

tr:last-child td { border-bottom: none; }

.mono { font-family: var(--font-mono); }
.loc { color: var(--accent); font-size: 0.82rem; }
.offsets { color: var(--text-muted); }

pre.snippet {
  font-family: var(--font-mono);
  font-size: 0.78rem;
  background: var(--code-bg);
  padding: 0.4rem 0.6rem;
  border-radius: var(--radius);
  overflow-x: auto;
  white-space: pre-wrap;
  word-break: break-all;
  max-width: 60ch;
  margin: 0;
  color: #c5cae9;
}

code {
  font-family: var(--font-mono);
  font-size: 0.85em;
  background: var(--code-bg);
  padding: 0.1em 0.35em;
  border-radius: 3px;
}

/* ── Misc ───────────────────────────────────────────────── */
.no-findings {
  color: var(--text-muted);
  font-style: italic;
  padding: 2rem 0;
  text-align: center;
}

.no-evidence {
  font-size: 0.82rem;
  color: var(--text-muted);
  margin-top: 0.5rem;
}

footer {
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border);
  font-size: 0.8rem;
  color: var(--text-muted);
  text-align: center;
}

/* ── Print ──────────────────────────────────────────────── */
@media print {
  :root {
    --bg: #fff; --surface: #f5f5f5; --surface2: #eee;
    --border: #ccc; --accent: #1a56db; --text: #111;
    --text-muted: #555; --code-bg: #f0f0f0;
  }
  body { max-width: 100%; padding: 0; }
  details.evidence { display: block; }
  details.evidence > summary { display: none; }
}
`.trim();
