/**
 * Canonical catalog of atomic API surface detectors.
 *
 * Each row describes one API surface (object, name, access kind). Matcher implementations
 * live under `matchers/`; this file is metadata only. Rows are validated and frozen at
 * load time — duplicate ids or invalid `apiKind` values throw immediately.
 *
 * @see ./detectorDefinition.js for row and match types
 */

import {validateApiDetectorRegistry} from './detectorDefinition.js';

/** @type {import('./detectorDefinition.js').ApiDetectorRow[]} */
const _registry = [

  // ── window geometry ──────────────────────────────────────────────────────
  {
    id: 'window-inner-width',
    title: 'window.innerWidth',
    category: 'window-geometry',
    apiObject: 'window',
    apiName: 'innerWidth',
    apiKind: 'property-read',
    description: 'Reads the viewport width (excluding browser chrome). Compared against outerWidth to detect open DevTools.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'window-outer-width',
    title: 'window.outerWidth',
    category: 'window-geometry',
    apiObject: 'window',
    apiName: 'outerWidth',
    apiKind: 'property-read',
    description: 'Reads the total browser window width (including chrome). Compared against innerWidth to detect open DevTools.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'window-inner-height',
    title: 'window.innerHeight',
    category: 'window-geometry',
    apiObject: 'window',
    apiName: 'innerHeight',
    apiKind: 'property-read',
    description: 'Reads the viewport height (excluding browser chrome). Compared against outerHeight to detect open DevTools.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'window-outer-height',
    title: 'window.outerHeight',
    category: 'window-geometry',
    apiObject: 'window',
    apiName: 'outerHeight',
    apiKind: 'property-read',
    description: 'Reads the total browser window height (including chrome). Compared against innerHeight to detect open DevTools.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'screen-width',
    title: 'screen.width',
    category: 'window-geometry',
    apiObject: 'screen',
    apiName: 'width',
    apiKind: 'property-read',
    description: 'Reads the physical screen width. Often used in fingerprinting or layout probing.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'screen-height',
    title: 'screen.height',
    category: 'window-geometry',
    apiObject: 'screen',
    apiName: 'height',
    apiKind: 'property-read',
    description: 'Reads the physical screen height. Often used in fingerprinting or layout probing.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'screen-avail-width',
    title: 'screen.availWidth',
    category: 'window-geometry',
    apiObject: 'screen',
    apiName: 'availWidth',
    apiKind: 'property-read',
    description: 'Reads the available screen width excluding taskbars. Used in fingerprinting.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'screen-avail-height',
    title: 'screen.availHeight',
    category: 'window-geometry',
    apiObject: 'screen',
    apiName: 'availHeight',
    apiKind: 'property-read',
    description: 'Reads the available screen height excluding taskbars. Used in fingerprinting.',
    extractsValue: false,
    extractedValueLabel: null,
  },

  // ── document props ────────────────────────────────────────────────────────
  {
    id: 'document-cookie-read',
    title: 'document.cookie (read)',
    category: 'document-props',
    apiObject: 'document',
    apiName: 'cookie',
    apiKind: 'property-read',
    description: 'Reads the document cookie string. May be parsed to extract individual cookie values.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'document-cookie-write',
    title: 'document.cookie (write)',
    category: 'document-props',
    apiObject: 'document',
    apiName: 'cookie',
    apiKind: 'property-write',
    description: 'Writes a cookie via document.cookie assignment. The cookie name can sometimes be extracted statically.',
    extractsValue: true,
    extractedValueLabel: 'cookie-name',
  },
  {
    id: 'document-domain',
    title: 'document.domain',
    category: 'document-props',
    apiObject: 'document',
    apiName: 'domain',
    apiKind: 'property-read',
    description: 'Reads or checks the current document domain. Used in cross-origin probing or iframe communication.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'document-referrer',
    title: 'document.referrer',
    category: 'document-props',
    apiObject: 'document',
    apiName: 'referrer',
    apiKind: 'property-read',
    description: 'Reads the referrer URL of the current document. Used in analytics, redirect logic, or origin detection.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'document-ready-state',
    title: 'document.readyState',
    category: 'document-props',
    apiObject: 'document',
    apiName: 'readyState',
    apiKind: 'property-read',
    description: 'Polls the document loading state. Commonly used to defer execution until the DOM is ready.',
    extractsValue: false,
    extractedValueLabel: null,
  },

  // ── storage ───────────────────────────────────────────────────────────────
  {
    id: 'local-storage-getitem',
    title: 'localStorage.getItem',
    category: 'storage',
    apiObject: 'localStorage',
    apiName: 'getItem',
    apiKind: 'method-call',
    description: 'Reads a value from localStorage by key name.',
    extractsValue: true,
    extractedValueLabel: 'key',
  },
  {
    id: 'local-storage-setitem',
    title: 'localStorage.setItem',
    category: 'storage',
    apiObject: 'localStorage',
    apiName: 'setItem',
    apiKind: 'method-call',
    description: 'Writes a value to localStorage under a key name.',
    extractsValue: true,
    extractedValueLabel: 'key',
  },
  {
    id: 'local-storage-removeitem',
    title: 'localStorage.removeItem',
    category: 'storage',
    apiObject: 'localStorage',
    apiName: 'removeItem',
    apiKind: 'method-call',
    description: 'Removes a key from localStorage.',
    extractsValue: true,
    extractedValueLabel: 'key',
  },
  {
    id: 'local-storage-clear',
    title: 'localStorage.clear',
    category: 'storage',
    apiObject: 'localStorage',
    apiName: 'clear',
    apiKind: 'method-call',
    description: 'Wipes all localStorage keys for the origin.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'session-storage-getitem',
    title: 'sessionStorage.getItem',
    category: 'storage',
    apiObject: 'sessionStorage',
    apiName: 'getItem',
    apiKind: 'method-call',
    description: 'Reads a value from sessionStorage by key name.',
    extractsValue: true,
    extractedValueLabel: 'key',
  },
  {
    id: 'session-storage-setitem',
    title: 'sessionStorage.setItem',
    category: 'storage',
    apiObject: 'sessionStorage',
    apiName: 'setItem',
    apiKind: 'method-call',
    description: 'Writes a value to sessionStorage under a key name.',
    extractsValue: true,
    extractedValueLabel: 'key',
  },
  {
    id: 'session-storage-removeitem',
    title: 'sessionStorage.removeItem',
    category: 'storage',
    apiObject: 'sessionStorage',
    apiName: 'removeItem',
    apiKind: 'method-call',
    description: 'Removes a key from sessionStorage.',
    extractsValue: true,
    extractedValueLabel: 'key',
  },

  // ── canvas ────────────────────────────────────────────────────────────────
  {
    id: 'canvas-get-context',
    title: 'canvas.getContext',
    category: 'canvas',
    apiObject: 'HTMLCanvasElement',
    apiName: 'getContext',
    apiKind: 'method-call',
    description: 'Requests a drawing context from a canvas element. The context type string (2d, webgl, webgl2, bitmaprenderer) is extracted when statically available.',
    extractsValue: true,
    extractedValueLabel: 'context-type',
  },
  {
    id: 'canvas-to-data-url',
    title: 'canvas.toDataURL',
    category: 'canvas',
    apiObject: 'HTMLCanvasElement',
    apiName: 'toDataURL',
    apiKind: 'method-call',
    description: 'Serializes canvas contents to a base64 data URL. A fingerprinting signal when combined with getContext and pixel drawing.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'canvas-get-image-data',
    title: 'CanvasRenderingContext2D.getImageData',
    category: 'canvas',
    apiObject: 'CanvasRenderingContext2D',
    apiName: 'getImageData',
    apiKind: 'method-call',
    description: 'Reads raw pixel data from the canvas. Used in canvas fingerprinting to capture rendering differences.',
    extractsValue: false,
    extractedValueLabel: null,
  },

  // ── prototype manipulation ────────────────────────────────────────────────
  {
    id: 'object-prototype-write',
    title: 'Object.prototype assignment',
    category: 'prototype',
    apiObject: 'Object',
    apiName: 'prototype',
    apiKind: 'property-write',
    description: 'Adds or overrides a property on Object.prototype, affecting all objects. A strong signal for prototype pollution or hook injection.',
    extractsValue: true,
    extractedValueLabel: 'property-name',
  },
  {
    id: 'function-prototype-write',
    title: 'Function.prototype assignment',
    category: 'prototype',
    apiObject: 'Function',
    apiName: 'prototype',
    apiKind: 'property-write',
    description: 'Adds or overrides a property on Function.prototype. Used to hook all function objects — a common anti-debugging technique.',
    extractsValue: true,
    extractedValueLabel: 'property-name',
  },
  {
    id: 'array-prototype-write',
    title: 'Array.prototype assignment',
    category: 'prototype',
    apiObject: 'Array',
    apiName: 'prototype',
    apiKind: 'property-write',
    description: 'Adds or overrides a property on Array.prototype. May override built-ins like map, filter, or forEach.',
    extractsValue: true,
    extractedValueLabel: 'property-name',
  },

  // ── navigator ─────────────────────────────────────────────────────────────
  {
    id: 'navigator-user-agent',
    title: 'navigator.userAgent',
    category: 'navigator',
    apiObject: 'navigator',
    apiName: 'userAgent',
    apiKind: 'property-read',
    description: 'Reads the browser user-agent string. Used in bot detection, browser sniffing, and fingerprinting.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'navigator-platform',
    title: 'navigator.platform',
    category: 'navigator',
    apiObject: 'navigator',
    apiName: 'platform',
    apiKind: 'property-read',
    description: 'Reads the OS/platform string. Used in environment probing and fingerprinting.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'navigator-hardware-concurrency',
    title: 'navigator.hardwareConcurrency',
    category: 'navigator',
    apiObject: 'navigator',
    apiName: 'hardwareConcurrency',
    apiKind: 'property-read',
    description: 'Reads the number of logical CPU cores. Used in fingerprinting or performance-adaptive behavior.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'navigator-languages',
    title: 'navigator.languages',
    category: 'navigator',
    apiObject: 'navigator',
    apiName: 'languages',
    apiKind: 'property-read',
    description: 'Reads the preferred language list. A fingerprinting signal for locale identification.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'navigator-plugins',
    title: 'navigator.plugins',
    category: 'navigator',
    apiObject: 'navigator',
    apiName: 'plugins',
    apiKind: 'property-read',
    description: 'Reads the installed browser plugins list. Historically used in fingerprinting; returns empty in modern headless environments.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'navigator-webdriver',
    title: 'navigator.webdriver',
    category: 'navigator',
    apiObject: 'navigator',
    apiName: 'webdriver',
    apiKind: 'property-read',
    description: 'Checks whether the browser is controlled by automation (Selenium/Puppeteer). True value signals a bot-detection check.',
    extractsValue: false,
    extractedValueLabel: null,
  },

  // ── network ───────────────────────────────────────────────────────────────
  {
    id: 'fetch-call',
    title: 'fetch()',
    category: 'network',
    apiObject: 'window',
    apiName: 'fetch',
    apiKind: 'method-call',
    description: 'Issues an HTTP request via the Fetch API. The URL is extracted when statically available.',
    extractsValue: true,
    extractedValueLabel: 'url',
  },
  {
    id: 'xhr-open',
    title: 'XMLHttpRequest.open',
    category: 'network',
    apiObject: 'XMLHttpRequest',
    apiName: 'open',
    apiKind: 'method-call',
    description: 'Configures an XHR request. The method and URL are extracted when statically available.',
    extractsValue: true,
    extractedValueLabel: 'url',
  },
  {
    id: 'websocket-constructor',
    title: 'new WebSocket()',
    category: 'network',
    apiObject: 'WebSocket',
    apiName: 'WebSocket',
    apiKind: 'constructor',
    description: 'Opens a persistent WebSocket connection. The URL is extracted when statically available.',
    extractsValue: true,
    extractedValueLabel: 'url',
  },

  // ── timing ────────────────────────────────────────────────────────────────
  {
    id: 'set-timeout',
    title: 'setTimeout',
    category: 'timing',
    apiObject: 'window',
    apiName: 'setTimeout',
    apiKind: 'method-call',
    description: 'Schedules a callback after a delay. Delay value is extracted when statically available.',
    extractsValue: true,
    extractedValueLabel: 'delay-ms',
  },
  {
    id: 'set-interval',
    title: 'setInterval',
    category: 'timing',
    apiObject: 'window',
    apiName: 'setInterval',
    apiKind: 'method-call',
    description: 'Schedules a recurring callback. Interval value is extracted when statically available.',
    extractsValue: true,
    extractedValueLabel: 'interval-ms',
  },
  {
    id: 'performance-now',
    title: 'performance.now',
    category: 'timing',
    apiObject: 'performance',
    apiName: 'now',
    apiKind: 'method-call',
    description: 'Reads a high-resolution timestamp. Used in timing attacks and DevTools detection via execution speed probing.',
    extractsValue: false,
    extractedValueLabel: null,
  },

  // ── workers ───────────────────────────────────────────────────────────────
  {
    id: 'worker-constructor',
    title: 'new Worker()',
    category: 'workers',
    apiObject: 'Worker',
    apiName: 'Worker',
    apiKind: 'constructor',
    description: 'Spawns a dedicated Web Worker. Script URL is extracted when statically available.',
    extractsValue: true,
    extractedValueLabel: 'script-url',
  },
  {
    id: 'shared-worker-constructor',
    title: 'new SharedWorker()',
    category: 'workers',
    apiObject: 'SharedWorker',
    apiName: 'SharedWorker',
    apiKind: 'constructor',
    description: 'Spawns a shared worker accessible across tabs. Script URL is extracted when statically available.',
    extractsValue: true,
    extractedValueLabel: 'script-url',
  },
  {
    id: 'service-worker-register',
    title: 'serviceWorker.register',
    category: 'workers',
    apiObject: 'ServiceWorkerContainer',
    apiName: 'register',
    apiKind: 'method-call',
    description: 'Registers a service worker. Script URL and scope are extracted when statically available.',
    extractsValue: true,
    extractedValueLabel: 'script-url',
  },

  // ── crypto ────────────────────────────────────────────────────────────────
  {
    id: 'crypto-get-random-values',
    title: 'crypto.getRandomValues',
    category: 'crypto',
    apiObject: 'crypto',
    apiName: 'getRandomValues',
    apiKind: 'method-call',
    description: 'Fills a typed array with cryptographically secure random values. Used in token generation or fingerprinting entropy.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'crypto-subtle-encrypt',
    title: 'crypto.subtle.encrypt',
    category: 'crypto',
    apiObject: 'SubtleCrypto',
    apiName: 'encrypt',
    apiKind: 'method-call',
    description: 'Performs symmetric encryption via the SubtleCrypto API.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'crypto-subtle-digest',
    title: 'crypto.subtle.digest',
    category: 'crypto',
    apiObject: 'SubtleCrypto',
    apiName: 'digest',
    apiKind: 'method-call',
    description: 'Computes a cryptographic hash. The algorithm name is extracted when statically available; used in fingerprinting or integrity checks.',
    extractsValue: true,
    extractedValueLabel: 'algorithm',
  },

  // ── dom injection ─────────────────────────────────────────────────────────
  {
    id: 'inner-html-write',
    title: 'innerHTML write',
    category: 'dom-injection',
    apiObject: 'Element',
    apiName: 'innerHTML',
    apiKind: 'property-write',
    description: 'Sets HTML content on an element via innerHTML. A risk vector for XSS and dynamic script injection.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'insert-adjacent-html',
    title: 'insertAdjacentHTML',
    category: 'dom-injection',
    apiObject: 'Element',
    apiName: 'insertAdjacentHTML',
    apiKind: 'method-call',
    description: 'Inserts HTML relative to an element. Equivalent risk to innerHTML for injected content.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'eval-call',
    title: 'eval()',
    category: 'dom-injection',
    apiObject: 'window',
    apiName: 'eval',
    apiKind: 'method-call',
    description: 'Evaluates a string as JavaScript. A primary obfuscation and code-injection mechanism.',
    extractsValue: false,
    extractedValueLabel: null,
  },
  {
    id: 'function-constructor',
    title: 'new Function()',
    category: 'dom-injection',
    apiObject: 'Function',
    apiName: 'Function',
    apiKind: 'constructor',
    description: 'Constructs a function from a string body. Functionally equivalent to eval for dynamic code execution.',
    extractsValue: false,
    extractedValueLabel: null,
  },
];

validateApiDetectorRegistry(_registry);

export const apiDetectorRegistry = Object.freeze(_registry.map(Object.freeze));

/** Stable set of all detector ids — used by capability registry validation. */
export const apiDetectorIds = new Set(apiDetectorRegistry.map((d) => d.id));
